---
title: "Group08 - 05_analysis_1"
subtitle: "Heat map plot"
author: "Vakare"
format: revealjs
editor: visual
---

## Load packages

```{r}
library("tidyverse")
```

## Load data

```{r}
heat_data <- read_tsv("../_raw/data/expression_with_metadata.tsv")
pnq_values <- read_csv("../_raw/data/05_analysis_4_results.csv")

heat_data
```

# Filter and clean up relevant data

```{r}
pnq_values
```

```{r}
filtered_heat_data <- heat_data |>
  filter(replicate == "Rep1") |>
  dplyr::select(gene, timepoint, condition, tissue, average) |>
  dplyr::rename(`timepoint [h]` = timepoint) |>                
  mutate(
    `timepoint [h]` = as.numeric(gsub("h", "", `timepoint [h]`))
    )

filtered_heat_data
```

## Calculate average expression per tissue and gene in control samples at 0h (Control baseline)

```{r}
control_means <- filtered_heat_data |>
  filter(condition == "control", `timepoint [h]` == 0) |>
  group_by(tissue, gene) |>  
  summarize(baseline_0h = mean(average, na.rm = TRUE), .groups = "drop")

control_means
```

## Calculating log2 fold change

```{r}
#calculate log2 fold change
heat_log2fc <- filtered_heat_data |>
  left_join(control_means, by = c("tissue", "gene")) |>
  mutate(log2FC = average - baseline_0h)


#Pick top 50 unique genes with the highest absolute log2 fold change values
top50_genes <- heat_log2fc |>
  mutate(abs_log2FC = abs(log2FC)) |> 
  group_by(gene) |>     
  slice_max(order_by = abs_log2FC, n = 1) |>   
  ungroup() |>
  arrange(desc(abs_log2FC)) |>                  
  slice_head(n = 50)                            

#Filter out irrelevant genes
filtered_heat_log2fc <- heat_log2fc |>
  filter(gene %in% top50_genes$gene, `timepoint [h]` != 0)
```

## Plotting heat map (Controls + Shoots)

```{r}
#setting up range for the FC legend
fc_limits <- range(filtered_heat_log2fc$log2FC)

heatmap_data1 <- filtered_heat_log2fc |>
  filter(condition == "control", tissue == "Shoots") |>
  mutate(
    gene = factor(gene, levels = unique(gene)),
    `timepoint [h]` = factor(`timepoint [h]`)  
  )

ggplot(heatmap_data1, aes(x = `timepoint [h]`, y = gene, fill = log2FC)) +
  geom_tile() +
  scale_fill_gradient2(
    low = "cyan",
    mid = "black",
    high = "deeppink",
    midpoint = 0,
    limits = fc_limits
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 5.5),
    plot.title = element_text(hjust = 0.5, face = "bold"),
    axis.title.x = element_text(vjust = -0.5)
  ) +
  labs(title = "Shoot gene expression over time (control conditions)",
       x = "Timepoint [h]",
       y = "Genes",
       fill = "Log2 Fold Change")
```

## Plotting heat map (Cold + Shoots)

```{r}
heatmap_data2 <- filtered_heat_log2fc |>
  filter(condition == "cold", tissue == "Shoots") |>
  mutate(
    gene = factor(gene, levels = unique(gene)),
    `timepoint [h]` = factor(`timepoint [h]`)  
  )

p1 <- ggplot(heatmap_data2, aes(x = `timepoint [h]`, y = gene, fill = log2FC)) +
  geom_tile() +
  scale_fill_gradient2(
    low = "cyan",
    mid = "black",
    high = "deeppink",
    midpoint = 0,
    limits = fc_limits
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 5.5),
    plot.title = element_text(hjust = 0.2, face = "bold"),
    axis.title.x = element_text(vjust = -0.5)
  ) +
  labs(title = "Shoot gene expression over time (cold conditions)",
       x = "Timepoint [h]", 
       y = "Genes", 
       fill = "Log2 Fold Change")
```

## Plotting heat map (Control + Roots)

```{r}
heatmap_data3 <- filtered_heat_log2fc |>
  filter(condition == "control", tissue == "Roots") |>
  mutate(
    gene = factor(gene, levels = unique(gene)),
    `timepoint [h]` = factor(`timepoint [h]`)  
  )

ggplot(heatmap_data3, aes(x = `timepoint [h]`, y = gene, fill = log2FC)) +
  geom_tile() +
  scale_fill_gradient2(
    low = "cyan",
    mid = "black",
    high = "deeppink",
    midpoint = 0,
    limits = fc_limits  # same log2 scale
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 5.5),
    plot.title = element_text(hjust = 0.2, face = "bold"),
    axis.title.x = element_text(vjust = -0.5)
  ) +
  labs(title = "Root gene expression over time (control conditions)",
       x = "Timepoint [h]",
       y = "Genes", 
       fill = "Log2 Fold Change")
```

## Plotting heat map (Cold + Roots)

```{r}
heatmap_data4 <- filtered_heat_log2fc |>
  filter(condition == "cold", tissue == "Roots") |>
  mutate(
    gene = factor(gene, levels = unique(gene)),
    `timepoint [h]` = factor(`timepoint [h]`)  
  )

ggplot(heatmap_data4, aes(x = `timepoint [h]`, y = gene, fill = log2FC)) +
  geom_tile() +
  scale_fill_gradient2(
    low = "cyan",
    mid = "black",
    high = "deeppink",
    midpoint = 0,
    limits = fc_limits  # same log2 scale
  ) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 5.5),
    plot.title = element_text(hjust = 0.2, face = "bold"),
    axis.title.x = element_text(vjust = -0.5),
  ) +
  labs(title = "Root gene expression over time (cold conditions)",
       x = "Timepoint [h]",
       y = "Genes",
       fill = "Log2 Fold Change")
```
